-- Enable extensions
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- Add embedding columns (1536 dims for text-embedding-3-small)
ALTER TABLE public.manual_sections
ADD COLUMN IF NOT EXISTS embedding_en vector(1536),
ADD COLUMN IF NOT EXISTS embedding_es vector(1536);

-- Create HNSW indexes for fast vector search
CREATE INDEX IF NOT EXISTS idx_manual_sections_embedding_en 
ON public.manual_sections 
USING hnsw (embedding_en vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS idx_manual_sections_embedding_es 
ON public.manual_sections 
USING hnsw (embedding_es vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- Update trigger to NULL embeddings when content changes
CREATE OR REPLACE FUNCTION public.update_manual_section_search_vectors()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
BEGIN
  -- Build English search vector
  NEW.search_vector_en := 
    setweight(to_tsvector('english', coalesce(NEW.title_en, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.content_en, '')), 'B') ||
    setweight(to_tsvector('english', array_to_string(NEW.tags, ' ')), 'C');
  
  -- Build Spanish search vector (with fallback to English)
  NEW.search_vector_es := 
    setweight(to_tsvector('spanish', coalesce(NEW.title_es, NEW.title_en, '')), 'A') ||
    setweight(to_tsvector('spanish', coalesce(NEW.content_es, NEW.content_en, '')), 'B') ||
    setweight(to_tsvector('spanish', array_to_string(NEW.tags, ' ')), 'C');
  
  -- NULL embeddings if content changed (will be regenerated by embed-sections)
  IF TG_OP = 'INSERT' OR 
     OLD.content_en IS DISTINCT FROM NEW.content_en OR
     OLD.content_es IS DISTINCT FROM NEW.content_es OR
     OLD.title_en IS DISTINCT FROM NEW.title_en OR
     OLD.title_es IS DISTINCT FROM NEW.title_es THEN
    IF NOT NEW.is_category THEN
      NEW.embedding_en := NULL;
      NEW.embedding_es := NULL;
    END IF;
  END IF;
  
  -- Update timestamp
  NEW.updated_at := now();
  
  RETURN NEW;
END;
$$;

-- Create hybrid search RPC function
CREATE OR REPLACE FUNCTION public.hybrid_search_manual(
  search_query TEXT,
  query_embedding vector(1536),
  search_language TEXT DEFAULT 'en',
  result_limit INT DEFAULT 10,
  keyword_weight FLOAT DEFAULT 0.4,
  vector_weight FLOAT DEFAULT 0.6
)
RETURNS TABLE (
  id UUID,
  slug TEXT,
  title TEXT,
  snippet TEXT,
  category TEXT,
  tags TEXT[],
  combined_score FLOAT,
  file_path TEXT
)
LANGUAGE plpgsql
STABLE SECURITY DEFINER
SET search_path = 'public'
AS $$
DECLARE
  ts_query tsquery;
  ts_config regconfig;
BEGIN
  IF search_language = 'es' THEN
    ts_config := 'spanish'::regconfig;
    ts_query := plainto_tsquery('spanish', search_query);
  ELSE
    ts_config := 'english'::regconfig;
    ts_query := plainto_tsquery('english', search_query);
  END IF;

  RETURN QUERY
  WITH 
  -- Keyword results with position
  kw AS (
    SELECT 
      ms.id,
      ROW_NUMBER() OVER (ORDER BY ts_rank(
        CASE WHEN search_language = 'es' THEN ms.search_vector_es ELSE ms.search_vector_en END,
        ts_query
      ) DESC) as pos
    FROM manual_sections ms
    WHERE ms.is_category = false
      AND CASE WHEN search_language = 'es' THEN ms.search_vector_es ELSE ms.search_vector_en END @@ ts_query
    LIMIT result_limit * 2
  ),
  
  -- Vector results with position
  vec AS (
    SELECT 
      ms.id,
      ROW_NUMBER() OVER (ORDER BY 
        CASE WHEN search_language = 'es' AND ms.embedding_es IS NOT NULL 
             THEN ms.embedding_es ELSE ms.embedding_en END <=> query_embedding
      ) as pos
    FROM manual_sections ms
    WHERE ms.is_category = false
      AND CASE WHEN search_language = 'es' AND ms.embedding_es IS NOT NULL 
               THEN ms.embedding_es ELSE ms.embedding_en END IS NOT NULL
    LIMIT result_limit * 2
  ),
  
  -- RRF combination: score = 1/(k + rank), k=60
  combined AS (
    SELECT 
      COALESCE(kw.id, vec.id) as id,
      (
        keyword_weight * COALESCE(1.0 / (60 + kw.pos), 0) +
        vector_weight * COALESCE(1.0 / (60 + vec.pos), 0)
      )::FLOAT as score
    FROM kw FULL OUTER JOIN vec ON kw.id = vec.id
  )
  
  SELECT 
    c.id,
    ms.slug,
    CASE WHEN search_language = 'es' AND ms.title_es IS NOT NULL THEN ms.title_es ELSE ms.title_en END,
    ts_headline(ts_config, 
      COALESCE(CASE WHEN search_language = 'es' AND ms.content_es IS NOT NULL THEN ms.content_es ELSE ms.content_en END, ''),
      ts_query, 'StartSel=<mark>, StopSel=</mark>, MaxWords=35, MinWords=15'),
    ms.category,
    ms.tags,
    c.score,
    ms.file_path
  FROM combined c
  JOIN manual_sections ms ON ms.id = c.id
  WHERE c.score > 0
  ORDER BY c.score DESC
  LIMIT result_limit;
END;
$$;