-- Reset all analyzed reviews to 'pending' so analyze-review re-processes them
-- with gpt-5-mini-2025-08-07. Also delete stale review_analyses rows so
-- the function writes fresh extractions.

BEGIN;

-- 1. Delete existing analyses (will be regenerated by the new model)
DELETE FROM public.review_analyses
WHERE review_id IN (
  SELECT id FROM public.restaurant_reviews
  WHERE analysis_status IN ('completed', 'failed', 'processing')
);

-- 2. Reset all reviews back to pending
UPDATE public.restaurant_reviews
SET analysis_status = 'pending',
    retry_count     = 0
WHERE analysis_status IN ('completed', 'failed', 'processing');

COMMIT;
